# -*- coding: utf-8 -*-
"""Birthday_guessing_game.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11vbA4B6kYNOPWGruwMcVQ_38x9wCSo08
"""

print("Welcome to the birthday guessing math magic game")
print("\n Think of your birth date \n")
print("\n Multiply by 2 \n")
print("\n Add result by 5 \n")
print("\n Multiply it by 100 \n")
print("\n Now add your birth month number \n")
print("\n After doing all that, enter your final number \n")

final_number = int(input("Enter your final result: "))

month = final_number % 100
day = (final_number // 100 - 5) // 2
print(f" \n I guess your birthday is on {day} / {month} ")