# -*- coding: utf-8 -*-
"""Flag_emoji.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qwaXtB-egbY7YB5MWJWVb1G2KDJWL3Fn
"""

import random
countries = {
    "india": "🇮🇳", "japan": "🇯🇵", "brazil": "🇧🇷", "canada": "🇨🇦", "france": "🇫🇷",
    "germany": "🇩🇪", "italy": "🇮🇹", "china": "🇨🇳", "nepal": "🇳🇵", "qatar": "🇶🇦",
    "australia": "🇦🇺", "spain": "🇪🇸", "usa": "🇺🇸", "mexico": "🇲🇽", "russia": "🇷🇺",
    "uk": "🇬🇧", "south korea": "🇰🇷", "saudi arabia": "🇸🇦", "argentina": "🇦🇷", "south africa": "🇿🇦"
}
print("\n Guess the Country from its Flag game! ")
print(" Type the country name.Example: japan, usa, india\n")
score = 0
while True:
  country = random.choice(list(countries.keys()))
  flag = countries[country]
  print("\n Flag: ", flag)
  guess = input("Ypur guess: ").strip().lower()

  if guess == country:
    print("Correct!")
    score +=1
  else:
    print( "Wrong! The correct answer was: ", country.upper())

  print("Current score: ",score)
  again = input(" Play again? (y/n): ").lower()
  if again != 'y':
    print("\n Final score: ",score)
    print("Thanks for playing! ")
    break